package com.hibernate.entity;

// Generated Sep 5, 2013 11:30:16 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer deptNo;
	private String deptName;
	private String location;
	private Set employees = new HashSet(0);
	
	public Department() {
	}

	public Department(String deptName, String location) {
		this.deptName = deptName;
		this.location = location;
	}

	public Department(String deptName, String location, Set employees) {
		this.deptName = deptName;
		this.location = location;
		this.employees = employees;
	}

	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
