package com.hibernate.entity;

// Generated Sep 5, 2013 11:30:16 AM by Hibernate Tools 4.0.0


/**
 * Employee generated by hbm2java
 */
public class EmployeeTransport implements java.io.Serializable {

	private Integer empNo;
	private Employee employee;
	private String carNo;
	
	public EmployeeTransport() {
	}

	public EmployeeTransport(Employee employee, String carNo) {
		super();
		this.employee = employee;
		this.carNo = carNo;
	}
	
	public Integer getEmpNo() {
		return empNo;
	}

	public void setEmpNo(Integer empNo) {
		this.empNo = empNo;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getCarNo() {
		return carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}
			
}
