package com.hibernate.entity;

// Generated Sep 5, 2013 11:30:16 AM by Hibernate Tools 4.0.0


/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer empNo;
	private Department department;
	private String empName;	;
	private String color;	
	private String food;
	private EmployeeTransport employeeTransport;	
	
	public Employee() {
	}

	public Employee(Department department, String empName) {
		this.department = department;
		this.empName = empName;
	}

	public Integer getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(Integer empNo) {
		this.empNo = empNo;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getFood() {
		return food;
	}

	public void setFood(String food) {
		this.food = food;
	}

	public EmployeeTransport getEmployeeTransport() {
		return employeeTransport;
	}

	public void setEmployeeTransport(EmployeeTransport employeeTransport) {
		this.employeeTransport = employeeTransport;
	}
	
}
