

import java.util.ArrayList;
import java.util.List;

import junit.framework.TestCase;

import com.xerox.enterprise.ghs.mmis.rif.common.exception.RIFException;
import com.xerox.enterprise.ghs.mmis.rif.core.RulesContext;
import com.xerox.enterprise.ghs.mmis.rif.core.RulesResult;
import com.xerox.enterprise.ghs.mmis.rif.core.api.RulesManager;

/**
 * The class <code></code> contains tests for the class
 * {@link <code>PGM4004_9005_NH01Test</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/25/14 8:19 PM
 *
 * @author 396662
 *
 * @version $Revision$
 */
public class PGM4004_9005_NH01Test extends TestCase {

	private boolean flag;

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public PGM4004_9005_NH01Test(String name) {
		super(name);
	}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = 
 * package.sourceFolder = MMIS_RIF_Rules/src
 * superclassType = junit.framework.TestCase
 * testCase = TPL0243_0002_01Test
 * testClassType = com.xerox.enterprise.ghs.mmis.rif.rules.automation.enterprise.PGM4004_9005_NH01
 */
public void testExecute() throws RIFException {
	int objSize = 6;	
     
    //Rule Invocation Context object holds object arrays used in rule execution.
	  			    //Name of the rule to be executed.
	    String ruleId = "PGM4004.9005.NH01";
	    RulesContext ric = new RulesContext();
	    //Adding object into rule invocation context.
	    String value="HCP";
	    List<String> systemList=new ArrayList();
	    systemList.add("HCP");
	    ric.addObject(value);
	    ric.addObject(systemList);
		boolean checkRange = false;
		//ric.addObject("AL3");
		
		    			
	  RulesManager rulesManager = RulesManager.getRIFInstance();
    
    //Invoke RIF with rulename and rule invocation objects.
	  			    RulesResult rulesResult = null;
	                
    try {
           						rulesResult = rulesManager.execute(ruleId, ric);	
			  					  						checkRange=rulesResult.isReturnBooleanValue(); 
			                } catch (RIFException re){
			                	re.printStackTrace();
    }
	  					if (!rulesResult.isReturnBooleanValue()) {
			  flag = false;
			}
	  		System.out.println("Rule boolean"+rulesResult.isReturnBooleanValue());
			assertTrue(checkRange);
	   	}	
    
}

